#!/bin/bash

sudo cp src/addhost /usr/bin/

if [ -f ~/.ssh/id_rsa.pub ]
then
	echo "OK."
else
	echo -e "直接回车\n"
	ssh-keygen -t rsa << EOF

y
EOF
	ssh-add ~/.ssh/id_rsa
fi

master=$(sed -n "4p" config.txt|awk '{print $1}')
pswd=$(sed -n "2p" config.txt|awk '{print $1}')

rm install-client

cat > install-client << EOF_INSTALL
#!/bin/bash

declare -a allip=(\$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'))

clientip=\${allip[0]}

if [ \$UID != 0 ]
then
	echo -e "You need to be root.\n"
	exit
fi

apt-get install -y hping3 nmap
useradd -d /opt/ddos ddos
mkdir /opt/ddos
chown ddos.ddos /opt/ddos
passwd ddos << EOF
$pswd
$pswd
EOF

cur=ddos@\$clientip
echo $cur
ssh $master "echo \$cur >> /tmp/hosts.txt; addhost"

EOF_INSTALL

cat src/install-template >> install-client

chmod +x install-client
