#!/bin/bash
declare -a HOSTS=($(cat /tmp/hosts.txt))
cnt=${#HOSTS[@]}

for ((i=0;i<cnt;i++)); do
	#cat ~/.ssh/id_rsa.pub | ssh ${HOSTS[i]} 'mkdir ~/.ssh; cat >> ~/.ssh/authorized_keys2; chmod 700 ~/.ssh; chmod 640 ~/.ssh/authorized_keys2'
	cat ~/.ssh/id_rsa.pub | ssh ${HOSTS[i]} 'mkdir ~/.ssh; cat >> ~/.ssh/authorized_keys2; chmod 700 ~/.ssh; chmod 640 ~/.ssh/authorized_keys2'
done
